//import { Inter } from "next/font/google";
//import "./globals.css";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import Box from "@mui/material/Box";
//
import MyStoreProvider from "../../redux/provider";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MyStoreProvider>
          <ThemeRegistry>
            <Box
              sx={{
                minHeight: "100vh",

                /* "@media screen and (min-width: 600px)": {
                minWidth: "600px",
                margin: 0,
              },*/

                overflow: "-moz-scrollbars-non",

                margin: 0 /* remove default margin */,
                scrollbarWidth:
                  "none" /* Also needed to disable scrollbar Firefox */,
                msOverflowStyle: "none" /* Disable scrollbar IE 10+ */,
                overflowY: "scroll",

                "&::-webkit-scrollbar": {
                  width: "0px",
                  background:
                    "transparent" /* Disable scrollbar Chrome/Safari/Webkit */,
                  display: "none",
                },
                // fontFamily: inter,
              }}
            >
              <Box
                component="main"
                role="main"
                tabIndex="-1"
                sx={{
                  outline: 0,
                  //
                  maxWidth: "1312px",
                }}
              >
                {children}
              </Box>
            </Box>
          </ThemeRegistry>
        </MyStoreProvider>
      </body>
    </html>
  );
}
